backend:
  name: github
  repo: bzzzx/blog
  branch: master
  base_url: https://blog-opal-zeta-16.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "博客文章"
    label_singular: "文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "标签", name: "tags", widget: "list", default: [] }
      - { label: "正文", name: "body", widget: "markdown" }
